apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app-service
  namespace: dev
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: app
  type: LoadBalancer