apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app-service
  namespace: dev
spec:
  ports:
    - port: 8765
      targetPort: 9376
  type: LoadBalancer
  selector:
    app: app
