apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app-service
  namespace: dev
spec:
  ports:
    - port: 8888
      targetPort: 8888
  type: LoadBalancer
  selector:
    app: app


---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: wil42/playground:v3
        name: app
