apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: wil42/playground:v1
        name: app
