apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app-service
  namespace: dev
spec:
  ports:
  - nodePort: 32322
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: app
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: wil42/playground:v1
        name: app